version: '3.8'
services:
  nacos-single:
    container_name: nacos-single
    image: nacos/nacos-server
    ports:
      - "8848:8848"
    restart: always
    environment:
      MODE: standalone


  mysql:
    container_name: mysql-cloud-3306
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/data/mysql/conf:/etc/mysql/conf.d
      - /var/data/mysql/logs:/logs
      - /var/data/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nacos
      MYSQL_ROOT_PASSWORD: root
    restart: always
    security_opt:
      - seccomp:unconfined

  redis:
    container_name: redis-single
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - /myredis/conf:/usr/local/etc/redis