server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://182.151.214.208:8989/test_jmbb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: cwxxhgs666
    driver-class-name: com.mysql.cj.jdbc.Driver
